#!/usr/bin/env python3
"""
Build the VCL-DEV-PMO-002 status report HTML with full VCL branding.

Embeds fonts (Manrope + JetBrains Mono) and the VCL stamp as base64 data URIs,
embeds the two mockup screenshots from briefs/screenshots/, and writes the
self-contained HTML to briefs/VCL-DEV-PMO-002_status_report.html.
"""
from pathlib import Path
import base64

REPO = Path('/home/tanujharia/projects/vcl-pmo')
B64 = Path('/tmp/b64')

def load_b64(name):
    return B64.joinpath(name).read_text()

def img_b64(p):
    return base64.b64encode(Path(p).read_bytes()).decode()

STAMP = load_b64('stamp.b64')
MR_400 = load_b64('manrope-400.b64')
MR_600 = load_b64('manrope-600.b64')
MR_700 = load_b64('manrope-700.b64')
MR_800 = load_b64('manrope-800.b64')
JB_400 = load_b64('jbmono-400.b64')
JB_700 = load_b64('jbmono-700.b64')

# Mockup screenshots — generated by Playwright in a prior step
SHOT_A = REPO / 'briefs/screenshots/mix-a.png'
SHOT_C = REPO / 'briefs/screenshots/mix-c.png'
shot_a_b64 = img_b64(SHOT_A) if SHOT_A.exists() else ''
shot_c_b64 = img_b64(SHOT_C) if SHOT_C.exists() else ''

# ---------------------------------------------------------------------------
# CSS — using Tanuj's palette (navy #0D1A2E + amber #F59E0B) with card/button
# styles lifted from mix-a.html (Steel/Mix-A).
# ---------------------------------------------------------------------------
CSS = r"""
@font-face { font-family: 'Manrope'; font-weight: 400; font-style: normal;
  src: url(data:font/ttf;base64,__MR_400__) format('truetype'); }
@font-face { font-family: 'Manrope'; font-weight: 600; font-style: normal;
  src: url(data:font/ttf;base64,__MR_600__) format('truetype'); }
@font-face { font-family: 'Manrope'; font-weight: 700; font-style: normal;
  src: url(data:font/ttf;base64,__MR_700__) format('truetype'); }
@font-face { font-family: 'Manrope'; font-weight: 800; font-style: normal;
  src: url(data:font/ttf;base64,__MR_800__) format('truetype'); }
@font-face { font-family: 'JetBrains Mono'; font-weight: 400; font-style: normal;
  src: url(data:font/ttf;base64,__JB_400__) format('truetype'); }
@font-face { font-family: 'JetBrains Mono'; font-weight: 700; font-style: normal;
  src: url(data:font/ttf;base64,__JB_700__) format('truetype'); }

:root {
  /* Tanuj-specified primary palette */
  --navy: #0D1A2E;
  --navy-dk: #07101F;
  --amber: #F59E0B;
  --amber-soft: rgba(245,158,11,0.16);
  --amber-line: rgba(245,158,11,0.4);

  /* Mockup palette (mix-a) — used for cards, chips, status colors */
  --blue: #2B3990;
  --blue-mid: #5C6DBE;
  --blue-light: #D6DBF5;
  --blue-pale: #EEF0FB;
  --sage: #5A9367;
  --green: #1B7A45;
  --green-light: #D4EDE0;
  --red: #C0392B;
  --red-light: #FADBD8;
  --ink: #1C1C1E;
  --mid: #4A4F5C;
  --muted: #8A909E;
  --rule: #E2E5ED;
  --surface: #FAFAFB;
  --paper: #FFFFFF;
}

* { box-sizing: border-box; }
html, body {
  margin: 0; padding: 0;
  font-family: 'Manrope', -apple-system, system-ui, sans-serif;
  color: var(--ink); background: var(--paper);
  font-size: 11pt; line-height: 1.5;
  letter-spacing: -0.005em;
}
.mono, code, kbd { font-family: 'JetBrains Mono', ui-monospace, monospace; font-size: 10.5pt; }

@page { size: A4 portrait; margin: 15mm 15mm 18mm 15mm; }
.page { page-break-after: always; padding: 0; }
.page:last-of-type { page-break-after: auto; }

/* ----- HEADER BAR ----- */
.bar {
  background: var(--navy); color: white;
  padding: 12px 18px; display: flex; align-items: center; justify-content: space-between;
  border-bottom: 3px solid var(--amber);
  font-size: 10.5pt; font-weight: 600; letter-spacing: 0.08em;
}
.bar .left { text-transform: uppercase; color: var(--amber); }
.bar .right { color: rgba(255,255,255,0.8); font-family: 'JetBrains Mono', monospace; font-size: 9.5pt; font-weight: 400; letter-spacing: 0.06em; }

/* ----- FOOTER BAR ----- */
.foot {
  background: var(--navy); color: rgba(255,255,255,0.85);
  padding: 8px 18px; display: flex; align-items: center; justify-content: space-between;
  border-top: 3px solid var(--amber);
  font-size: 9pt; font-family: 'JetBrains Mono', monospace; letter-spacing: 0.05em;
  margin-top: 18px;
}
.foot .stamp-mini { width: 32px; height: 32px; opacity: 0.95; }

/* ----- COVER ----- */
.cover {
  background: var(--navy); color: white;
  min-height: 268mm;
  padding: 24mm 18mm 18mm 18mm;
  display: flex; flex-direction: column; justify-content: space-between;
  margin: -15mm; /* full bleed */
  position: relative;
}
.cover-stripe-top { height: 6px; background: var(--amber); margin: -24mm -18mm 24mm -18mm; }
.cover .org-line {
  display: flex; justify-content: space-between; align-items: flex-start;
  margin-bottom: 18mm;
}
.cover .org-line .caps {
  color: var(--amber);
  font-family: 'Manrope', sans-serif;
  font-weight: 700;
  font-size: 11pt;
  letter-spacing: 0.32em;
  text-transform: uppercase;
}
.cover .org-line .stamp img { width: 120px; height: 120px; }
.cover .title { font-family: 'Manrope', sans-serif; font-weight: 800; font-size: 56pt; line-height: 1.0; letter-spacing: -0.02em; color: white; }
.cover .lede { font-size: 16pt; color: rgba(255,255,255,0.78); line-height: 1.45; max-width: 520px; margin-top: 14px; font-weight: 400; }
.cover .accent-rule { height: 4px; background: var(--amber); width: 80px; margin: 30px 0; }
.cover .meta-grid {
  display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 22px 32px;
  background: rgba(255,255,255,0.05);
  border: 1px solid rgba(245,158,11,0.32);
  border-radius: 8px;
  padding: 22px 24px;
  margin-top: 26px;
}
.cover .meta-grid .k {
  font-family: 'JetBrains Mono', monospace;
  font-size: 9pt;
  color: var(--amber);
  text-transform: uppercase;
  letter-spacing: 0.12em;
  font-weight: 600;
  margin-bottom: 4px;
}
.cover .meta-grid .v {
  font-family: 'Manrope', sans-serif;
  font-size: 13.5pt;
  color: white;
  font-weight: 600;
}
.cover .cover-foot {
  margin-top: auto;
  border-top: 1px solid rgba(245,158,11,0.4);
  padding-top: 14px;
  display: flex; justify-content: space-between; align-items: center;
  color: rgba(255,255,255,0.7);
  font-family: 'JetBrains Mono', monospace;
  font-size: 9.5pt;
  letter-spacing: 0.06em;
}
.cover .cover-foot .confidential { color: var(--amber); font-weight: 700; }

/* ----- BODY PAGES ----- */
h1 { font-family: 'Manrope', sans-serif; font-weight: 800; font-size: 26pt; color: var(--navy); letter-spacing: -0.015em; margin: 22px 0 8px 0; line-height: 1.1; }
h2 { font-family: 'Manrope', sans-serif; font-weight: 700; font-size: 15pt; color: var(--navy); margin: 24px 0 10px 0; padding-bottom: 6px; border-bottom: 2px solid var(--amber); letter-spacing: -0.01em; }
h3 { font-family: 'Manrope', sans-serif; font-weight: 700; font-size: 12pt; color: var(--navy); margin: 16px 0 6px 0; letter-spacing: -0.005em; }
.sub { color: var(--muted); font-size: 11pt; margin-top: -2px; font-weight: 400; }
p { margin: 8px 0; }
ul, ol { margin: 8px 0 12px 22px; padding: 0; }
li { margin: 4px 0; }

/* ----- KPI / STATUS CARDS (mix-a pattern) ----- */
.kpis { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; margin: 14px 0 22px 0; }
.kpi {
  background: var(--paper);
  border: 1px solid var(--rule);
  border-top: 3px solid var(--navy);
  border-radius: 8px;
  padding: 16px 18px;
  page-break-inside: avoid;
}
.kpi .l { font-size: 9pt; text-transform: uppercase; letter-spacing: 0.1em; color: var(--muted); font-weight: 700; }
.kpi .v { font-family: 'JetBrains Mono', monospace; font-size: 30pt; font-weight: 500; color: var(--navy); letter-spacing: -0.02em; margin-top: 6px; line-height: 1; }
.kpi .d { font-size: 10pt; color: var(--mid); margin-top: 6px; }
.kpi.green { border-top-color: var(--green); }
.kpi.green .v { color: var(--green); }
.kpi.amber { border-top-color: var(--amber); }
.kpi.amber .v { color: var(--amber); }
.kpi.red { border-top-color: var(--red); }
.kpi.red .v { color: var(--red); }
.kpi.slate { border-top-color: var(--muted); }
.kpi.slate .v { color: var(--mid); }

/* ----- CHIPS (mix-a) ----- */
.chip { display: inline-flex; align-items: center; gap: 5px; font-size: 9.5pt; font-weight: 700; padding: 2px 9px; border-radius: 11px; letter-spacing: 0.02em; border: 1px solid transparent; }
.chip i { width: 6px; height: 6px; border-radius: 50%; display: inline-block; }
.chip.green { background: var(--green-light); color: var(--green); border-color: #bfe2cd; } .chip.green i { background: var(--green); }
.chip.amber { background: var(--amber-soft); color: #B86B00; border-color: var(--amber-line); } .chip.amber i { background: var(--amber); }
.chip.muted { background: var(--surface); color: var(--mid); border-color: var(--rule); } .chip.muted i { background: var(--muted); }
.chip.blue  { background: var(--blue-light); color: var(--blue); border-color: #bec7ea; } .chip.blue i { background: var(--blue); }
.chip.red   { background: var(--red-light); color: var(--red); border-color: #f1bcb4; } .chip.red i { background: var(--red); }

/* ----- BUTTONS (mix-a) ----- */
.btn { font-size: 10pt; font-weight: 600; padding: 6px 12px; border-radius: 5px; border: 1px solid var(--rule); color: var(--ink); background: var(--paper); display: inline-flex; align-items: center; gap: 6px; letter-spacing: -0.005em; }
.btn.primary { background: var(--navy); color: white; border-color: var(--navy); }
.btn.amber   { background: var(--amber); color: var(--navy); border-color: var(--amber); }
.btn.ghost   { border-color: transparent; color: var(--muted); }

/* ----- TABLE (mix-a) ----- */
table.tbl { width: 100%; border-collapse: separate; border-spacing: 0; background: var(--paper); border: 1px solid var(--rule); border-radius: 8px; overflow: hidden; font-size: 10.5pt; margin: 10px 0 16px 0; }
table.tbl th { background: var(--navy); color: white; font-weight: 700; font-size: 9pt; text-transform: uppercase; letter-spacing: 0.06em; text-align: left; padding: 9px 13px; }
table.tbl td { padding: 10px 13px; border-top: 1px solid var(--rule); color: var(--ink); vertical-align: top; }
table.tbl tr:first-child td { border-top: 0; }
table.tbl td.id-cell { font-family: 'JetBrains Mono', monospace; font-size: 10pt; color: var(--navy); font-weight: 700; }
table.tbl td.who { color: var(--mid); font-style: italic; width: 100px; }
table.tbl td.when { width: 80px; color: var(--muted); font-family: 'JetBrains Mono', monospace; font-size: 10pt; }

/* ----- CARDS / SUMMARY ----- */
.card { background: var(--paper); border: 1px solid var(--rule); border-radius: 8px; padding: 16px 18px; margin: 12px 0; }
.summary-box {
  border-left: 4px solid var(--amber);
  background: #FFFDF7;
  padding: 14px 18px;
  margin: 14px 0 18px 0;
  border-radius: 4px;
}
.summary-box b { color: var(--navy); }

/* ----- QA BLOCKS ----- */
.qa { background: var(--surface); border-left: 4px solid var(--navy); padding: 11px 14px; border-radius: 4px; margin: 8px 0; font-size: 11pt; }
.qa b { color: var(--navy); margin-right: 4px; }

/* ----- DIAGRAMS ----- */
svg.diagram { display: block; margin: 14px auto; max-width: 100%; height: auto; }
.caption { font-size: 9.5pt; color: var(--muted); text-align: center; margin-top: -2px; font-style: italic; }

/* ----- SCREENSHOTS ----- */
.screenshot {
  background: var(--paper);
  border: 1px solid var(--rule);
  border-radius: 8px;
  overflow: hidden;
  margin: 14px 0;
  page-break-inside: avoid;
}
.screenshot .frame { padding: 8px 10px; background: var(--navy); color: white; font-size: 10pt; display: flex; justify-content: space-between; align-items: center; }
.screenshot .frame .url { font-family: 'JetBrains Mono', monospace; font-size: 9pt; color: rgba(255,255,255,0.65); }
.screenshot img { display: block; width: 100%; height: auto; }
.screenshot .caption-row { padding: 8px 12px; font-size: 10pt; color: var(--mid); border-top: 1px solid var(--rule); background: var(--surface); }

/* ----- SIGNOFF ----- */
.signature { margin-top: 30px; padding-top: 16px; border-top: 1px solid var(--rule); font-size: 10.5pt; color: var(--muted); display: grid; grid-template-columns: 1fr 1fr; gap: 30px; }
.signature .slot { border-bottom: 1px solid var(--ink); padding-bottom: 32px; margin-bottom: 6px; }

/* ----- PRINT ----- */
@media print {
  body { background: white; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
  .cover { color: white; background: var(--navy) !important; }
  .bar, .foot { background: var(--navy) !important; color: white !important; }
  table.tbl th { background: var(--navy) !important; color: white !important; }
  h1, h2, h3 { page-break-after: avoid; }
  p, li { orphans: 3; widows: 3; }
  .kpi, .card, .screenshot, .qa, .summary-box, table.tbl tr { page-break-inside: avoid; }
}
"""

# ---------------------------------------------------------------------------
# SVG diagrams
# ---------------------------------------------------------------------------

AGENT_LOOP_SVG = r"""
<svg class="diagram" viewBox="0 0 720 380" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Agent loop swimlane">
  <defs>
    <marker id="arrA" viewBox="0 0 12 12" refX="11" refY="6" markerWidth="9" markerHeight="9" orient="auto">
      <path d="M0,0 L12,6 L0,12 z" fill="#0D1A2E"/>
    </marker>
  </defs>
  <!-- lanes -->
  <rect x="0" y="0"   width="720" height="76"  fill="#FAFAFB" stroke="#E2E5ED"/>
  <rect x="0" y="76"  width="720" height="76"  fill="#FFFFFF" stroke="#E2E5ED"/>
  <rect x="0" y="152" width="720" height="76"  fill="#FAFAFB" stroke="#E2E5ED"/>
  <rect x="0" y="228" width="720" height="76"  fill="#FFFFFF" stroke="#E2E5ED"/>
  <rect x="0" y="304" width="720" height="76"  fill="#FAFAFB" stroke="#E2E5ED"/>
  <!-- lane labels -->
  <g font-family="Manrope, sans-serif" font-weight="700" font-size="11" fill="#0D1A2E">
    <text x="12" y="44">Tanuj</text>
    <text x="12" y="120">PMO system</text>
    <text x="12" y="196">Agent (Claude / Codex)</text>
    <text x="12" y="272">UAT / OAT</text>
    <text x="12" y="348">Slack / Excel</text>
  </g>
  <!-- nodes -->
  <g font-family="Manrope, sans-serif" font-size="11" text-anchor="middle">
    <rect x="120" y="14" width="120" height="48" fill="#0D1A2E" rx="6"/>
    <text x="180" y="38" fill="white" font-weight="700">1. Write plan</text>
    <text x="180" y="54" fill="rgba(255,255,255,0.8)" font-size="10">in /app/pmo</text>

    <rect x="280" y="90" width="120" height="48" fill="#F59E0B" rx="6"/>
    <text x="340" y="114" fill="#0D1A2E" font-weight="700">2. Allocate items</text>
    <text x="340" y="130" fill="#0D1A2E" font-size="10">claude / codex / human</text>

    <rect x="440" y="90" width="120" height="48" fill="#0D1A2E" rx="6"/>
    <text x="500" y="114" fill="white" font-weight="700">3. Dispatch shift</text>
    <text x="500" y="130" fill="rgba(255,255,255,0.8)" font-size="10">via n8n webhook</text>

    <rect x="440" y="166" width="120" height="48" fill="#0D1A2E" rx="6"/>
    <text x="500" y="190" fill="white" font-weight="700">4. Agent works</text>
    <text x="500" y="206" fill="rgba(255,255,255,0.8)" font-size="10">commits + writes notes</text>

    <rect x="280" y="166" width="120" height="48" fill="#F59E0B" rx="6"/>
    <text x="340" y="190" fill="#0D1A2E" font-weight="700">5. Complete shift</text>
    <text x="340" y="206" fill="#0D1A2E" font-size="10">writes UAT/OAT runs</text>

    <rect x="280" y="242" width="120" height="48" fill="#0D1A2E" rx="6"/>
    <text x="340" y="266" fill="white" font-weight="700">6. UAT walk</text>
    <text x="340" y="282" fill="rgba(255,255,255,0.8)" font-size="10">Tanuj signs off</text>

    <rect x="440" y="318" width="120" height="48" fill="#F59E0B" rx="6"/>
    <text x="500" y="342" fill="#0D1A2E" font-weight="700">7. Slack mirror</text>
    <text x="500" y="358" fill="#0D1A2E" font-size="10">plan PDF posted</text>

    <rect x="120" y="318" width="120" height="48" fill="#0D1A2E" rx="6"/>
    <text x="180" y="342" fill="white" font-weight="700">Excel mirror</text>
    <text x="180" y="358" fill="rgba(255,255,255,0.8)" font-size="10">via n8n</text>
  </g>
  <g stroke="#0D1A2E" stroke-width="1.5" fill="none" marker-end="url(#arrA)">
    <line x1="240" y1="38" x2="340" y2="86"/>
    <line x1="400" y1="114" x2="438" y2="114"/>
    <line x1="500" y1="138" x2="500" y2="164"/>
    <line x1="440" y1="190" x2="402" y2="190"/>
    <line x1="340" y1="214" x2="340" y2="240"/>
    <line x1="400" y1="266" x2="500" y2="316"/>
    <line x1="180" y1="62"  x2="180" y2="316"/>
  </g>
</svg>
"""

ARCH_SVG = r"""
<svg class="diagram" viewBox="0 0 720 240" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Two anchor model">
  <defs>
    <marker id="arrB" viewBox="0 0 12 12" refX="11" refY="6" markerWidth="9" markerHeight="9" orient="auto">
      <path d="M0,0 L12,6 L0,12 z" fill="#8A909E"/>
    </marker>
  </defs>
  <g font-family="Manrope, sans-serif" font-size="11" text-anchor="middle">
    <rect x="60"  y="60" width="220" height="120" rx="10" fill="#0D1A2E" stroke="#F59E0B" stroke-width="2"/>
    <text x="170" y="94" fill="white" font-weight="800" font-size="14">ERPNext (Frappe Cloud)</text>
    <text x="170" y="116" fill="rgba(255,255,255,0.8)">PMO doctypes · /app/pmo</text>
    <text x="170" y="134" fill="rgba(255,255,255,0.8)">Plans · Shifts · Tasks</text>
    <text x="170" y="152" fill="rgba(255,255,255,0.8)">UAT · OAT · RAID · Notes</text>
    <rect x="80" y="160" width="180" height="20" rx="4" fill="#F59E0B"/>
    <text x="170" y="174" fill="#0D1A2E" font-weight="800" font-size="10" letter-spacing="0.15em">SOURCE OF TRUTH</text>

    <rect x="440" y="20" width="220" height="80" rx="10" fill="#F59E0B"/>
    <text x="550" y="50" fill="#0D1A2E" font-weight="800" font-size="14">Slack #ai-pmo-plans</text>
    <text x="550" y="70" fill="#0D1A2E">Plan PDFs · approvals</text>
    <text x="550" y="86" fill="#0D1A2E">read on reMarkable / Boox</text>

    <rect x="440" y="140" width="220" height="80" rx="10" fill="#FFFFFF" stroke="#0D1A2E" stroke-width="2"/>
    <text x="550" y="170" fill="#0D1A2E" font-weight="800" font-size="14">Excel mirror</text>
    <text x="550" y="190" fill="#4A4F5C">monthly slice on the share</text>
    <text x="550" y="206" fill="#4A4F5C">written by n8n, read-only</text>
  </g>
  <g stroke="#8A909E" stroke-width="1.5" fill="none" marker-end="url(#arrB)">
    <line x1="280" y1="100" x2="438" y2="60"/>
    <line x1="280" y1="140" x2="438" y2="180"/>
  </g>
</svg>
"""

BUTTON_FLOW_SVG = r"""
<svg class="diagram" viewBox="0 0 720 470" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Button flow in /app/pmo">
  <defs>
    <style>
      .btn-pri  { fill: #0D1A2E; rx: 5; }
      .btn-amb  { fill: #F59E0B; }
      .btn-out  { fill: #FFFFFF; stroke: #E2E5ED; stroke-width: 1.2; }
      .btn-txt  { fill: white; font: 600 11px Manrope, sans-serif; }
      .btn-txt-d { fill: #0D1A2E; font: 600 11px Manrope, sans-serif; }
      .num      { fill: #F59E0B; font: 700 12px 'JetBrains Mono', monospace; }
      .lbl      { fill: #0D1A2E; font: 600 11.5px Manrope, sans-serif; }
      .sub      { fill: #8A909E; font: 10.5px Manrope, sans-serif; }
    </style>
  </defs>

  <text x="60"  y="34" class="num">01</text>
  <text x="90"  y="34" class="lbl">Open /app/pmo and pick the project</text>
  <rect x="60"  y="46" width="180" height="30" rx="5" class="btn-out"/>
  <text x="150" y="66" class="btn-txt-d" text-anchor="middle">VCL PMO System</text>
  <text x="60"  y="92" class="sub">Lands on the project page with all the tabs across the top.</text>

  <text x="60"  y="120" class="num">02</text>
  <text x="90"  y="120" class="lbl">Plans tab — start a new plan</text>
  <rect x="60"  y="132" width="130" height="30" rx="5" class="btn-pri"/>
  <text x="125" y="152" class="btn-txt" text-anchor="middle">+ New Plan</text>
  <text x="60"  y="178" class="sub">Modal opens. You type a title + description, click Save.</text>

  <text x="60"  y="206" class="num">03</text>
  <text x="90"  y="206" class="lbl">Add items to the plan</text>
  <rect x="60"  y="218" width="130" height="30" rx="5" class="btn-pri"/>
  <text x="125" y="238" class="btn-txt" text-anchor="middle">+ Add Item</text>
  <text x="210" y="238" class="sub">Each item picks a type (Shift, Task, Milestone, RAID...).</text>

  <text x="60"  y="270" class="num">04</text>
  <text x="90"  y="270" class="lbl">Push the plan to Slack as a branded PDF</text>
  <rect x="60"  y="282" width="180" height="30" rx="5" class="btn-amb"/>
  <text x="150" y="302" class="btn-txt-d" text-anchor="middle">Send PDF to Slack</text>
  <text x="260" y="302" class="sub">Lands in #ai-pmo-plans, reads cleanly on reMarkable.</text>

  <text x="60"  y="334" class="num">05</text>
  <text x="90"  y="334" class="lbl">Tick items, allocate to an agent or human</text>
  <rect x="60"  y="346" width="160" height="30" rx="5" class="btn-out"/>
  <text x="140" y="366" class="btn-txt-d" text-anchor="middle">Allocate to Claude</text>
  <rect x="230" y="346" width="160" height="30" rx="5" class="btn-out"/>
  <text x="310" y="366" class="btn-txt-d" text-anchor="middle">Allocate to Codex</text>
  <rect x="400" y="346" width="160" height="30" rx="5" class="btn-out"/>
  <text x="480" y="366" class="btn-txt-d" text-anchor="middle">Allocate to Human</text>
  <text x="60"  y="392" class="sub">Items become Shifts. Each Shift auto-creates its UAT/OAT records, bucketed under the shift.</text>

  <text x="60"  y="416" class="num">06</text>
  <text x="90"  y="416" class="lbl">Send the shift to the agent</text>
  <rect x="60"  y="428" width="180" height="30" rx="5" class="btn-pri"/>
  <text x="150" y="448" class="btn-txt" text-anchor="middle">Execute via n8n</text>
  <text x="260" y="448" class="sub">Agent picks it up, works, commits, then calls Complete back into ERPNext.</text>
</svg>
"""

# ---------------------------------------------------------------------------
# Build pages
# ---------------------------------------------------------------------------

def bar(left, right):
    return f'<div class="bar"><span class="left">{left}</span><span class="right">{right}</span></div>'

def foot(left):
    return f'<div class="foot"><span>{left}</span><img class="stamp-mini" src="data:image/png;base64,{STAMP}" alt="VCL"/></div>'

COVER = f"""
<section class="page">
  <div class="cover">
    <div class="cover-stripe-top"></div>
    <div class="org-line">
      <div class="caps">Vimit Converters Limited</div>
      <div class="stamp"><img src="data:image/png;base64,{STAMP}" alt="VCL Stamp"/></div>
    </div>
    <div>
      <div class="title">VCL PMO System</div>
      <div class="lede">A single, plain-English status pack for the project we are using to build the system that runs all our other projects.</div>
      <div class="accent-rule"></div>
      <div class="meta-grid">
        <div><div class="k">Project ID</div><div class="v">VCL-DEV-PMO-002</div></div>
        <div><div class="k">Sponsor</div><div class="v">Tanuj Haria</div></div>
        <div><div class="k">Phase</div><div class="v">Phase 2 — Build</div></div>
        <div><div class="k">Started</div><div class="v">27 May 2026</div></div>
        <div><div class="k">Target finish</div><div class="v">7 June 2026</div></div>
        <div><div class="k">This report</div><div class="v">28 May 2026</div></div>
      </div>
    </div>
    <div class="cover-foot">
      <span>Prepared by Claude · for review on reMarkable / Boox Air 5</span>
      <span class="confidential">CONFIDENTIAL · VCL INTERNAL</span>
    </div>
  </div>
</section>
"""

P2_STATUS = f"""
<section class="page">
  {bar('VCL PMO · Status Report', 'page 02 · 28 may 2026')}
  <div style="padding:0 6mm;">
  <h1>Where we are today</h1>
  <div class="sub">Status as at 21:30 EAT, 28 May 2026.</div>

  <div class="kpis">
    <div class="kpi green"><div class="l">Done</div><div class="v">2</div><div class="d">work blocks shipped</div></div>
    <div class="kpi amber"><div class="l">In flight</div><div class="v">1</div><div class="d">waiting on one setup step</div></div>
    <div class="kpi amber"><div class="l">Waiting</div><div class="v">1</div><div class="d">design write-up pending</div></div>
    <div class="kpi green"><div class="l">Health</div><div class="v" style="font-size:18pt;">On track</div><div class="d">target 7 Jun stands</div></div>
  </div>

  <div class="summary-box">
    <b>One sentence:</b> The PMO is being built inside ERPNext as the new home for all VCL development work — so plans, tasks, agents, testing and approvals all live in one place. As of today, four of the four planned work blocks are either shipped or coded; the only remaining steps before the system is end-to-end operational are one Slack token install and one design write-up.
  </div>

  <h2>What we just finished</h2>
  <table class="tbl">
    <thead><tr><th style="width:32%;">What</th><th>Why it matters</th><th style="width:90px;">Status</th></tr></thead>
    <tbody>
      <tr>
        <td><b>Back button works everywhere</b></td>
        <td>Pressing browser Back from any sub-page now returns to the right tab instead of landing on a "page not available" error. Reload and pasted links also work.</td>
        <td><span class="chip green"><i></i>DONE</span></td>
      </tr>
      <tr>
        <td><b>Tests are grouped by what they test</b></td>
        <td>Instead of one long flat list of UAT/OAT items, each shift's tests sit under a clear header showing pass/fail/blocked counts. Easier to walk through, easier to sign off.</td>
        <td><span class="chip green"><i></i>DONE</span></td>
      </tr>
    </tbody>
  </table>

  <h2>What is built but waiting on one setup</h2>
  <table class="tbl">
    <thead><tr><th style="width:32%;">What</th><th>Why it matters</th><th style="width:32%;">What it needs</th></tr></thead>
    <tbody>
      <tr>
        <td><b>Plans go to Slack as PDFs</b></td>
        <td>One click renders any plan as a clean, A4, VCL-branded PDF and drops it in <code>#ai-pmo-plans</code>. Sized for reading and annotating on reMarkable or Boox Air 5.</td>
        <td>Install a Slack bot token in the site settings, invite the bot to the channel. About 10 minutes of admin.</td>
      </tr>
    </tbody>
  </table>

  <h2>What is still on the drawing board</h2>
  <table class="tbl">
    <thead><tr><th style="width:32%;">What</th><th>Why it matters</th><th style="width:30%;">Owner</th></tr></thead>
    <tbody>
      <tr>
        <td><b>Auto-review of new plans by agents</b></td>
        <td>Today every new plan needs Tanuj to manually choose Claude / Codex / human for each item. The design will let an agent draft the proposed allocation overnight and send Tanuj a single Approve button.</td>
        <td>Codex — design only, not code, by 30 May</td>
      </tr>
    </tbody>
  </table>
  </div>
  {foot('VCL PMO · VCL-DEV-PMO-002 · 28 May 2026')}
</section>
"""

P3_WORKFLOW = f"""
<section class="page">
  {bar('VCL PMO · How it works', 'page 03 · 28 may 2026')}
  <div style="padding:0 6mm;">
  <h1>How it works — the buttons in order</h1>
  <div class="sub">The whole system is driven by six buttons in the PMO page at /app/pmo. Navy = primary action; amber = brand action; outline = secondary.</div>

  {BUTTON_FLOW_SVG}
  <p class="caption">Figure 1. The six clicks from idea to running shift.</p>

  <h2>Then the agent loop fires</h2>
  <p>Once a shift is dispatched, the rest of the cycle runs without you. Each lane below is one actor; arrows show the handover.</p>

  {AGENT_LOOP_SVG}
  <p class="caption">Figure 2. One full loop from plan to signed-off tests, mirrored to Slack and Excel.</p>
  </div>
  {foot('VCL PMO · VCL-DEV-PMO-002 · 28 May 2026')}
</section>
"""

P4_ARCH = f"""
<section class="page">
  {bar('VCL PMO · Architecture', 'page 04 · 28 may 2026')}
  <div style="padding:0 6mm;">
  <h1>Where each piece lives</h1>
  <p>We deliberately do <i>not</i> try to put everything in one tool. The principle is two anchors: ERPNext is the operational source of truth for project work, and Slack + Excel exist as downstream review surfaces that already work for the team.</p>

  {ARCH_SVG}
  <p class="caption">Figure 3. One source of truth, two downstream review surfaces. No reverse writes from Slack or Excel back into ERPNext.</p>

  <h3>What that means in practice</h3>
  <ul>
    <li><b>You edit in ERPNext.</b> Everything else mirrors automatically.</li>
    <li><b>Slack is for reading and annotating.</b> Plans land there as PDFs; nothing in Slack writes back.</li>
    <li><b>Excel is for the monthly slice.</b> n8n writes a workbook per project on the share; you never edit it directly.</li>
    <li><b>Agents talk to ERPNext directly</b> via whitelisted API methods. n8n is the routing layer, not a data store.</li>
  </ul>
  </div>
  {foot('VCL PMO · VCL-DEV-PMO-002 · 28 May 2026')}
</section>
"""

# Screenshots page — only if both screenshots exist
SCREENSHOT_BLOCK_A = f"""
<div class="screenshot">
  <div class="frame"><span><b>Mockup A — Steel</b></span><span class="url">mockups/mix-a.html</span></div>
  <img src="data:image/png;base64,{shot_a_b64}" alt="Mix A screenshot"/>
  <div class="caption-row">The Steel mockup: light surface, navy / amber accents, KPI tiles, requirement inbox. This is the styling reference for the report you're reading.</div>
</div>
""" if shot_a_b64 else ""

SCREENSHOT_BLOCK_C = f"""
<div class="screenshot">
  <div class="frame"><span><b>Mockup C — Pulse</b></span><span class="url">mockups/mix-c.html</span></div>
  <img src="data:image/png;base64,{shot_c_b64}" alt="Mix C screenshot"/>
  <div class="caption-row">The Pulse mockup: dark theme, live ticker, sparkline KPIs. Alternate visual treatment proposed but not built into /app/pmo yet.</div>
</div>
""" if shot_c_b64 else ""

P5_VISUALS = f"""
<section class="page">
  {bar('VCL PMO · Visual reference', 'page 05 · 28 may 2026')}
  <div style="padding:0 6mm;">
  <h1>Visual reference</h1>
  <p>The PMO interface inside ERPNext follows a deliberate style language. These are the two mockups we built before settling on a direction. The live system follows the <b>Mix A — Steel</b> palette: light surface, navy frame, amber accents.</p>
  {SCREENSHOT_BLOCK_A}
  {SCREENSHOT_BLOCK_C}
  </div>
  {foot('VCL PMO · VCL-DEV-PMO-002 · 28 May 2026')}
</section>
""" if (shot_a_b64 or shot_c_b64) else ""

P6_NEXT = f"""
<section class="page">
  {bar('VCL PMO · What comes next', 'page 06 · 28 may 2026')}
  <div style="padding:0 6mm;">
  <h1>What comes next</h1>

  <h2>Before this Friday (29–30 May)</h2>
  <table class="tbl">
    <thead><tr><th class="who" style="width:110px;">Owner</th><th>Action</th><th class="when">By</th></tr></thead>
    <tbody>
      <tr><td class="who">Tanuj</td><td>Install a Slack bot in the workspace, drop its token into the PMO site settings, invite it to <b>#ai-pmo-plans</b>.</td><td class="when">29 May</td></tr>
      <tr><td class="who">Tanuj</td><td>Walk the back-button fix on three real flows (Plans → Plan, Shifts → Shift, UAT case detail). Sign off SHIFT-0001.</td><td class="when">29 May</td></tr>
      <tr><td class="who">Tanuj</td><td>Once the bot is in: click <b>Send PDF to Slack</b> on one plan. Confirm it lands and reads cleanly on reMarkable. Sign off SHIFT-0003.</td><td class="when">29 May</td></tr>
      <tr><td class="who">Codex</td><td>Write the spec for "auto-review of new plans" — six points, no code. Lands as a markdown doc in the repo.</td><td class="when">30 May</td></tr>
    </tbody>
  </table>

  <h2>Following week (2–7 June)</h2>
  <table class="tbl">
    <thead><tr><th class="who" style="width:140px;">Owner</th><th>Action</th><th class="when">By</th></tr></thead>
    <tbody>
      <tr><td class="who">Tanuj</td><td>Review the auto-review spec, mark it Pass, hand off to Claude or Codex to build.</td><td class="when">2 Jun</td></tr>
      <tr><td class="who">Tanuj</td><td>Close the Phase 2 Foundation milestone (MS-PMO-001). System officially the master for development work.</td><td class="when">3 Jun</td></tr>
      <tr><td class="who">Claude or Codex</td><td>Build the scheduled plan-review job (nightly sweep, capacity-aware routing, single approve action).</td><td class="when">5 Jun</td></tr>
      <tr><td class="who">Tanuj</td><td>UAT the scheduled job end-to-end. Mark project Done.</td><td class="when">7 Jun</td></tr>
    </tbody>
  </table>

  <h2>Open questions for Tanuj</h2>
  <div class="qa"><b>Q1.</b> Slack bot — create a new one called <i>VCL PMO Bot</i>, or reuse an existing workspace bot? (Recommend new, so scopes stay minimal.)</div>
  <div class="qa"><b>Q2.</b> Auto-review trigger — every 6 hours, nightly at 23:00, or hourly when an unallocated plan appears? (Recommend nightly 23:00.)</div>
  <div class="qa"><b>Q3.</b> Capacity probe for Codex — manual flag in site settings, or external monitor file? (Recommend manual flag this round.)</div>
  <div class="qa"><b>Q4.</b> Where do approvals live — Slack with a button, Telegram with a reply, or just the Plans tab? (Recommend Slack with a permalink back to /app/pmo.)</div>

  <div class="signature">
    <div>
      <div class="slot">&nbsp;</div>
      <div>Tanuj Haria — Sponsor</div>
    </div>
    <div>
      <div class="slot">&nbsp;</div>
      <div>Date</div>
    </div>
  </div>
  </div>
  {foot('VCL PMO · VCL-DEV-PMO-002 · 28 May 2026')}
</section>
"""

# ---------------------------------------------------------------------------
# Assemble
# ---------------------------------------------------------------------------

HTML = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>VCL PMO System — Status Report</title>
<style>{CSS
  .replace('__MR_400__', MR_400)
  .replace('__MR_600__', MR_600)
  .replace('__MR_700__', MR_700)
  .replace('__MR_800__', MR_800)
  .replace('__JB_400__', JB_400)
  .replace('__JB_700__', JB_700)
}</style>
</head>
<body>
{COVER}
{P2_STATUS}
{P3_WORKFLOW}
{P4_ARCH}
{P5_VISUALS}
{P6_NEXT}
</body>
</html>
"""

out = REPO / 'briefs/VCL-DEV-PMO-002_status_report.html'
out.write_text(HTML)
print(f"wrote {out} ({len(HTML):,} bytes)")
